import { execFile } from "child_process";
import path from "path";
import fs from "fs";

const ext = (f) => path.extname(f).toLowerCase();

/**
 * Trim a single media file.
 * @param {string} inputPath
 * @param {string} outputPath
 * @param {number} start     - Start time in seconds (default: 0)
 * @param {number|null} end  - End time in seconds, or null to trim to end of file
 */
function trimFile(inputPath, outputPath, start = 0, end = null) {
  const duration = end !== null ? end - start : null;
  const sameFormat = ext(inputPath) === ext(outputPath);

  const args = [
    "-y",
    "-i", inputPath,
    "-ss", String(start),
    ...(duration !== null ? ["-t", String(duration)] : []),
    ...(sameFormat ? ["-acodec", "copy"] : []),
    outputPath,
  ];

  return new Promise((resolve, reject) => {
    execFile("ffmpeg", args, (error, _stdout, stderr) => {
      if (error) {
        reject(new Error(`ffmpeg error on ${inputPath}: ${stderr || error.message}`));
      } else {
        resolve(outputPath);
      }
    });
  });
}

/**
 * Write an ESM index file that exports the list of output filenames.
 * @param {string} dir
 * @param {string[]} filenames
 */
function writeIndexFile(dir, filenames) {
  const indexPath = path.join(dir, "index-files.mjs");
  const content = [
    `// Auto-generated by trim-media.mjs`,
    `export function files() {`,
    `  return ${JSON.stringify(filenames, null, 2)};`,
    `}`,
    `export default files;`,
    "",
  ].join("\n");
  fs.writeFileSync(indexPath, content, "utf8");
  return indexPath;
}

/**
 * Trim one file or all media files in a directory.
 * @param {string} input     - Input file or directory
 * @param {string} output    - Output file or directory
 * @param {number} start     - Start time in seconds (default: 0)
 * @param {number|null} end  - End time in seconds, or null for end of file
 */
async function trimMedia(input, output, start = 0, end = null) {
  const inputStat = fs.statSync(input);

  if (inputStat.isDirectory()) {
    fs.mkdirSync(output, { recursive: true });

    const entries = fs.readdirSync(input).filter((f) => {
      const e = ext(f);
      return [".mp3", ".mp4", ".aac", ".ogg", ".wav", ".flac", ".m4a", ".webm"].includes(e);
    });

    if (entries.length === 0) {
      throw new Error(`No supported media files found in: ${input}`);
    }

    const outputFiles = [];

    for (const filename of entries) {
      const inputFile = path.join(input, filename);
      const outputFile = path.join(output, filename);
      await trimFile(inputFile, outputFile, start, end);
      console.log(`Trimmed: ${filename}`);
      outputFiles.push(filename);
    }

    const indexPath = writeIndexFile(output, outputFiles);
    console.log(`Index written: ${indexPath}`);

    return outputFiles;
  } else {
    await trimFile(input, output, start, end);
    console.log(`Done! Saved to: ${output}`);
    return output;
  }
}

// --- CLI ---
const [input, output, startArg, endArg] = process.argv.slice(2);

if (!input || !output) {
  console.error("Usage: node trim-media.mjs <input.(mp3|dir)> <output.(mp3|dir)> [start] [end]");
  process.exit(1);
}

const start = startArg ? parseFloat(startArg) : 0;
const end = endArg ? parseFloat(endArg) : null;

trimMedia(path.resolve(input), path.resolve(output), start, end).catch((err) => {
  console.error("Error:", err.message);
  process.exit(1);
});
