// @ts-check


import { version } from 'node:process';
console.log('Actual Node.js version:', version);

import { execFile } from "child_process";
import path from "path";
// console.log("my name", path.basename(import.meta.url));
import fs from "fs";

import { styleText } from 'node:util';

//#region STyled logging
////////////////////////////////////////////////////
/////// Styled logging with line number in this file
////////////////////////////////////////////////////
/** @typedef {(...args: any[]) => void} StyledLogger */
/** @type {StyledLogger} */
function logRed(...args) { const fun = (text) => styleText("red", text); logLineStyled(fun, ...args); }
/** @type {StyledLogger} */
function logGreen(...args) { const fun = (text) => styleText("green", text); logLineStyled(fun, ...args); }
/** @type {StyledLogger} */
function logYellow(...args) { const fun = (text) => styleText("yellow", text); logLineStyled(fun, ...args); }
/** @type {StyledLogger} */
function logBlue(...args) { const fun = (text) => styleText("blueBright", text); logLineStyled(fun, ...args); }

/**
 * Logs a styled message with a line prefix.
 * @param {StyledLogger} funStyle - Function that applies styling to text
 * @param {...any} args - Arguments to log after the styled prefix
 */
function logLineStyled(funStyle, ...args) {
  console.log(funStyle(getLine() + ":"), ...args);
}

let debugGetLine = false;
function logDebugGetLine(...args) {
  if (!debugGetLine) return;
  console.log("LOG-DEBUG-GL: ", ...args);
}
function getLine() {
  try {
    throw Error("getLine");
  } catch (err) {
    const stack = err.stack;
    const arr = stack.split("\n");
    let iFile = -1;
    for (let i = 0; i < arr.length; i++) {
      const arr2 = arr[i].trim();
      logDebugGetLine("arr2", i, arr2);
      if (arr2.startsWith("at file:/")) {
        logDebugGetLine({ iFile });
        iFile = i;
        break;
      }
    }
    iFile = 4;
    const arr2 = arr[iFile].trim();
    const re = /:(\d+):\d+/;
    const m = arr2.match(re);
    const lineNum = m[1];
    return lineNum;
  }
}
//#endregion

// console.log(chalk.blue("trim-media.mjs loading...\n"));
console.log(styleText(["blueBright", "bold"], "trim-media.mjs loading...\n"));

// --- CLI ---
const [input, output, startArg, durationArg] = process.argv.slice(2);

if (!input || !output) {
  console.error("Usage: node trim-media.mjs <input.(mp3|dir)> <output.(mp3|dir)> [start] [end]");
  process.exit(1);
}


/** * @param {string} f * @returns {string} */
const ext = (f) => path.extname(f).toLowerCase();

/**
 * Trim a single media file.
 * @param {string} inputPath
 * @param {string} outputPath
 * @param {number} start     - Start time in seconds (default: 0)
 * @param {number|null} end  - End time in seconds, or null to trim to end of file
 */
function trimFile(inputPath, outputPath, start = 0, end = null) {
  logGreen("trimFile", { start, end });
  const duration = end !== null ? end - start : null;
  const sameFormat = ext(inputPath) === ext(outputPath);

  const args = [
    "-y",
    "-i", inputPath,
    "-ss", String(start),
    ...(duration !== null ? ["-t", String(duration)] : []),
    ...(sameFormat ? ["-acodec", "copy"] : []),
    outputPath,
  ];

  return new Promise((resolve, reject) => {
    // console.warn("WARN execFile ffmpeg:", { args });
    logYellow("execFile ffmpeg:", args.map(a => a.slice(0, 8)).join(" "));
    execFile("ffmpeg", args, (error, _stdout, stderr) => {
      if (error) {
        reject(new Error(`ffmpeg error on ${inputPath}: ${stderr || error.message}`));
      } else {
        resolve(outputPath);
      }
    });
  });
}

let strOptionsForFiles;
const optionsFilename = path.join(input, "../AAAoptions.txt");
try {
  strOptionsForFiles = fs.readFileSync(optionsFilename, 'utf8');
  logBlue(strOptionsForFiles);
} catch (err) {
  console.warn(err);
  strOptionsForFiles = "";
}
const arrOptionsForFiles = strOptionsForFiles ? strOptionsForFiles.split("\n").sort() : [];
const divider = ";;";


/** @param {string} filename * @returns {string|undefined} */
function getFileOptionsRow(filename) {
  let rowOption;
  arrOptionsForFiles.forEach(row => {
    if (row.startsWith(`${filename}${divider}`)) { rowOption = row; }
  });
  return rowOption;
}

/**
 * Write an ESM index file that exports the list of output filenames.
 * @param {string} dir
 * @param {string[]} filenames
 */
function writeIndexFile(dir, filenames) {
  const indexPath = path.join(dir, "index-files.mjs");
  const filenamesAndUInames = filenames.map(filename => {
    return getFileOptionsRow(filename);
  });
  const content = [
    `// Auto-generated by trim-media.mjs`,
    `export function files() {`,
    `  return ${JSON.stringify(filenamesAndUInames, null, 2)};`,
    `}`,
    `export function myUrl(filename) {`,
    `  return new URL(filename, import.meta.url).href;`,
    `}`,
    `export default files;`,
    "",
  ].join("\n");
  fs.writeFileSync(indexPath, content, "utf8");
  return indexPath;
}

/**
 * Trim one file or all media files in a directory.
 * @param {string} input     - Input file or directory
 * @param {string} output    - Output file or directory
 * @param {number} start     - Start time in seconds (default: 0)
 * @param {number|null} duration  - End time in seconds, or null for end of file
 */
async function trimMedia(input, output, start = 0, duration = 10) {
  const inputStat = fs.statSync(input);

  if (inputStat.isDirectory()) {
    fs.mkdirSync(output, { recursive: true });

    const entries = fs.readdirSync(input).filter((f) => {
      const e = ext(f);
      return [".mp3", ".mp4", ".aac", ".ogg", ".wav", ".flac", ".m4a", ".webm"].includes(e);
    });

    if (entries.length === 0) {
      throw new Error(`No supported media files found in: ${input}`);
    }

    const outputFiles = [];


    for (const filename of entries) {
      const oldRowOption = getFileOptionsRow(filename);
      // debugGetLine = true;
      logGreen("oldRowOption: ", oldRowOption);
      debugGetLine = false;
      if (!oldRowOption) {
        arrOptionsForFiles.push([filename, "0", ""].join(divider));
      } else {

      }
      const rowOption = getFileOptionsRow(filename);
      if (!rowOption) throw Error(`rowOption == "${rowOption}"`);
      const [_fn, startOpt, _ui] = rowOption.split(";;");
      logGreen("startOpt", startOpt);

      let startSound = startOpt;

      const inputFile = path.join(input, filename);
      const outputFile = path.join(output, filename);
      await trimFile(inputFile, outputFile, startSound, duration);
      console.log(`Trimmed: ${filename}`);
      outputFiles.push(filename);

    }

    function writeOptionsForFiles() {
      const strNewOptionsForFiles = arrOptionsForFiles.join("\n");
      try {
        fs.writeFileSync(optionsFilename, strNewOptionsForFiles, 'utf8');
      } catch (err) {
        console.error(err);
        throw err;
      }
      return optionsFilename;
    }

    const indexPath = writeIndexFile(output, outputFiles);
    console.log(`Index written: ${indexPath}`);

    const optionsPath = writeOptionsForFiles();
    console.log(`Options for files written: ${optionsPath}`);

    return outputFiles;
  } else {
    await trimFile(input, output, start, duration);
    console.log(`Done! Saved to: ${output}`);
    return output;
  }
}


const start = startArg ? parseFloat(startArg) : 0;
const duration = durationArg ? parseFloat(durationArg) : null;

trimMedia(path.resolve(input), path.resolve(output), start, duration).catch((err) => {
  console.error("Error:", err.message);
  process.exit(1);
});
